CREATE TABLE CATEGORY(
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ITEM (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL,
    IMAGE_NAME VARCHAR(MAX),
    ACTIVE BOOLEAN,
    AMOUNT INT,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);